/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PaquetCliente;

import PaqueteInterfaceFrameCliente.EventEstadoConexion;
import PaqueteInterfaceFrameCliente.EventMessageSG;
import PaqueteInterfaceFrameCliente.EventUserAceppt;
import PaqueteInterfaceFrameCliente.InterfaceFrameCliente;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;

/**
 *
 * @author Christian
 */
public class Launch extends javax.swing.JFrame implements InterfaceFrameCliente {

    Cliente cliente;
    Login login;
    Sesión registrar;
    JTable tabla;

    /**
     * Creates new form Launch
     */
    public Launch() {
        initComponents();
        labelEstado.setOpaque(true);
        labelEstado.setText("...............DESCONECTADO...............");
        labelEstado.setBackground(Color.red);
        this.cliente = new Cliente("localhost", 5000);
        this.cliente.iniciar();
        this.cliente.addMyEventListener(this);
        this.login = new Login();
        this.registrar = new Sesión();
        btnIniciar.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelEstado = new javax.swing.JLabel();
        btnLoginL = new javax.swing.JButton();
        btnRegisterL = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        labelConectados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelEstado.setBackground(new java.awt.Color(255, 51, 51));
        labelEstado.setText("DESCONECTADO");

        btnLoginL.setText("LOGIN");
        btnLoginL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginLActionPerformed(evt);
            }
        });

        btnRegisterL.setText("REGISTER");
        btnRegisterL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterLActionPerformed(evt);
            }
        });

        btnIniciar.setText("INICIAR");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegisterL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLoginL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnIniciar)
                        .addGap(39, 39, 39)
                        .addComponent(labelConectados)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciar)
                    .addComponent(labelConectados))
                .addGap(43, 43, 43)
                .addComponent(btnLoginL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegisterL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginLActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        //this.cliente.removeMyEventListener(this);
        this.setVisible(false);
        login.setLaunch(this);
        login.setSesión(registrar);
        login.setEstado(labelEstado.getText(), labelEstado.getBackground());
        login.setCliente(this.cliente);
        login.setVisible(true);

    }//GEN-LAST:event_btnLoginLActionPerformed

    private void btnRegisterLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterLActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        registrar.setLaunch(this);
        registrar.setLogin(login);
        registrar.setEstado(labelEstado.getText(), labelEstado.getBackground());
        registrar.setCliente(this.cliente);
        registrar.setVisible(true);

    }//GEN-LAST:event_btnRegisterLActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        
         SwingUtilities.invokeLater(() -> {
            MiVentana ventana = new MiVentana();
            ventana.setVisible(true);
        });
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Launch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Launch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Launch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Launch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Launch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnLoginL;
    private javax.swing.JButton btnRegisterL;
    private javax.swing.JLabel labelConectados;
    private javax.swing.JLabel labelEstado;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onEstado(EventEstadoConexion evento) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        System.out.println("evento: " + evento.getEstado());
        labelEstado.setOpaque(true);
        btnLoginL.setEnabled(evento.getEstado());
        btnRegisterL.setEnabled(evento.getEstado());
        if (evento.getEstado()) {
            System.out.println("SE CONECTA DESDE EL FRAME");
            labelEstado.setText("...............CONECTADO...............");
            labelEstado.setBackground(Color.green);

        } else {
            System.out.println("entraaaa");
            labelEstado.setText("...............DESCONECTADO...............");
            labelEstado.setBackground(Color.red);

        }
    }

    @Override
    public void onAcceptUser(EventUserAceppt evento) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        if (evento.getAccept()) {
            btnLoginL.setVisible(false);
            btnRegisterL.setVisible(false);
            btnIniciar.setVisible(true);

            // cliente.executeNickname();
            // labelUsuario.setText(cliente.getNickname());
        }
    }

    @Override
    public void onMessageSG(EventMessageSG evento) {
        // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        labelConectados.setOpaque(true);
        labelConectados.setForeground(Color.green);
        labelConectados.setText(evento.getMessage() + " usuarios conectados");

    }
}
