/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PaquetCliente;

import PaqueteInterfaceFrameCliente.EventEstadoConexion;
import PaqueteInterfaceFrameCliente.EventMessageSG;
import PaqueteInterfaceFrameCliente.EventUserAceppt;
import PaqueteInterfaceFrameCliente.InterfaceFrameCliente;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Christian
 */
public class Sesión extends javax.swing.JFrame implements InterfaceFrameCliente {

    Cliente cliente;
    Launch launch;
    Login login;

    /**
     * Creates new form Sesión
     */
    public Sesión() {
        initComponents();

    }

    public void setLogin(Login l) {
        this.login = l;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
        this.cliente.addMyEventListener(this);
    }

    public void setLaunch(Launch launch) {
        this.launch = launch;
    }

    public void setEstado(String msje, Color color) {
        labelEstadoRegister.setOpaque(true);
        labelEstadoRegister.setText(msje);
        labelEstadoRegister.setBackground(color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNickname = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRegistrarR = new javax.swing.JButton();
        btnLoginR = new javax.swing.JButton();
        labelEstadoRegister = new javax.swing.JLabel();
        labelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Registrar");

        jLabel2.setText("Nickname");

        jLabel3.setText("Password");

        btnRegistrarR.setText("Registrar");
        btnRegistrarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRActionPerformed(evt);
            }
        });

        btnLoginR.setText("Login");
        btnLoginR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginRActionPerformed(evt);
            }
        });

        labelEstadoRegister.setBackground(new java.awt.Color(255, 51, 51));
        labelEstadoRegister.setText("DESCONECTADO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(labelEstadoRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLoginR))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelError)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNickname, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnRegistrarR, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnLoginR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnRegistrarR)
                .addGap(44, 44, 44)
                .addComponent(labelEstadoRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRActionPerformed
        // TODO add your handling code here:
        cliente.registrar(txtNickname.getText(), txtPassword.getText());
    }//GEN-LAST:event_btnRegistrarRActionPerformed

    private void btnLoginRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginRActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        login.setLaunch(launch);
        login.setSesión(this);
        login.setEstado(labelEstadoRegister.getText(), labelEstadoRegister.getBackground());
        login.setCliente(this.cliente);
        login.setVisible(true);
    }//GEN-LAST:event_btnLoginRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sesión.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sesión.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sesión.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sesión.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sesión().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoginR;
    private javax.swing.JButton btnRegistrarR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelEstadoRegister;
    private javax.swing.JTextField txtNickname;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onEstado(EventEstadoConexion evento) {
        labelEstadoRegister.setOpaque(true);
        if (evento.getEstado()) {
            labelEstadoRegister.setText("...............CONECTADO...............");
            labelEstadoRegister.setBackground(Color.green);
            btnLoginR.setEnabled(true);
            btnRegistrarR.setEnabled(true);
        } else {
            labelEstadoRegister.setText("...............DESCONECTADO...............");
            labelEstadoRegister.setBackground(Color.red);
            btnLoginR.setEnabled(false);
            btnRegistrarR.setEnabled(false);

        }
    }

    @Override
    public void onAcceptUser(EventUserAceppt evento) {
        if (evento.getTipo().equals("R")) {
            labelError.setVisible(true);
            labelError.setOpaque(true);
            if (!evento.getAccept()) {

                labelError.setForeground(Color.red);
                labelError.setText("ERROR:El Nickname ya está en uso");
            } else {
                labelError.setForeground(Color.green);
                labelError.setText("LOGIN EXITOSO");
                launch.setVisible(true);
                this.setVisible(false);
            }
        }
    }

    @Override
    public void onMessageSG(EventMessageSG evento) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
